from device import create_device
import formulas
from dense_graph_annealer import dense_graph_annealer
from dense_graph_bf_searcher import dense_graph_bf_searcher
from bipartite_graph_annealer import bipartite_graph_annealer
from bipartite_graph_bf_searcher import bipartite_graph_bf_searcher

device = create_device(0)
